"""Initial schema.

Creates every table in §2 plus gateway_credentials, users and benchmark_runs.

Two things worth knowing if you extend this:

* Enum-valued columns are String + CheckConstraint rather than native Postgres
  enums, so adding an operation for a new gateway is an ordinary migration
  instead of a non-transactional ALTER TYPE that cannot be downgraded.
* transactions has a UNIQUE (gateway_id, idempotency_key). That constraint --
  not the service layer's check -- is what makes §0.6 hold under a race.

Revision ID: 0001_initial
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gateways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('integration_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.CheckConstraint("code IN ('HPP', 'DIRECT_API', 'TOKEN_CIT', 'TOKEN_MIT', 'TOKENIZE')", name='ck_integration_types_code'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('benchmark_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gateway_id', sa.Integer(), nullable=False),
    sa.Column('integration_type_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stop_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("operation IN ('AUTH', 'SALE', 'CAPTURE', 'PARTIAL_CAPTURE', 'REFUND', 'PARTIAL_REFUND', 'VOID', 'TOKENIZE', 'CIT_CHARGE', 'MIT_CHARGE', 'ORDER_QUERY')", name='ck_benchmark_runs_operation'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateways.id'], ),
    sa.ForeignKeyConstraint(['integration_type_id'], ['integration_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_benchmark_runs_gateway_started', 'benchmark_runs', ['gateway_id', 'started_at'], unique=False)
    op.create_table('gateway_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gateway_id', sa.Integer(), nullable=False),
    sa.Column('key_name', sa.String(length=128), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('is_production', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateways.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_id', 'key_name', name='uq_gateway_credential')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gateway_id', sa.Integer(), nullable=False),
    sa.Column('integration_type_id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('parent_transaction_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('captured_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('refunded_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('card_brand', sa.String(length=32), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('card_exp_month', sa.Integer(), nullable=True),
    sa.Column('card_exp_year', sa.Integer(), nullable=True),
    sa.Column('token_reference', sa.String(length=255), nullable=True),
    sa.Column('gateway_order_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('merchant_reference', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("operation IN ('AUTH', 'SALE', 'CAPTURE', 'PARTIAL_CAPTURE', 'REFUND', 'PARTIAL_REFUND', 'VOID', 'TOKENIZE', 'CIT_CHARGE', 'MIT_CHARGE', 'ORDER_QUERY')", name='ck_transactions_operation'),
    sa.CheckConstraint("status IN ('PENDING', 'SUCCESS', 'FAILED', 'ERROR', 'TIMEOUT')", name='ck_transactions_status'),
    sa.CheckConstraint('amount_minor >= 0', name='ck_transactions_amount_nonneg'),
    sa.CheckConstraint('captured_amount_minor >= 0 AND refunded_amount_minor >= 0', name='ck_transactions_totals_nonneg'),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateways.id'], ),
    sa.ForeignKeyConstraint(['integration_type_id'], ['integration_types.id'], ),
    sa.ForeignKeyConstraint(['parent_transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_id', 'idempotency_key', name='uq_transaction_idempotency')
    )
    op.create_index('ix_transactions_gateway_created', 'transactions', ['gateway_id', 'created_at'], unique=False)
    op.create_index('ix_transactions_gateway_order_id', 'transactions', ['gateway_order_id'], unique=False)
    op.create_index('ix_transactions_merchant_reference', 'transactions', ['merchant_reference'], unique=False)
    op.create_index('ix_transactions_status', 'transactions', ['status'], unique=False)
    op.create_table('api_call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('gateway_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=64), nullable=False),
    sa.Column('http_method', sa.String(length=8), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('request_headers_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('request_body_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_headers_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('response_body_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('timeout_seconds', sa.Float(), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateways.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'sequence_number', name='uq_api_call_sequence')
    )
    op.create_index('ix_api_call_logs_gateway_started', 'api_call_logs', ['gateway_id', 'started_at'], unique=False)
    op.create_index('ix_api_call_logs_transaction', 'api_call_logs', ['transaction_id', 'sequence_number'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gateway_id', sa.Integer(), nullable=False),
    sa.Column('token_reference', sa.String(length=255), nullable=False),
    sa.Column('card_brand', sa.String(length=32), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('card_exp_month', sa.Integer(), nullable=True),
    sa.Column('card_exp_year', sa.Integer(), nullable=True),
    sa.Column('created_from_transaction_id', sa.Integer(), nullable=True),
    sa.Column('agreement_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_from_transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateways.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_id', 'token_reference', name='uq_token_reference')
    )
    op.create_table('webhooks_received',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gateway_id', sa.Integer(), nullable=False),
    sa.Column('headers_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('body_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('matched_transaction_id', sa.Integer(), nullable=True),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('event_reference', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['webhooks_received.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateways.id'], ),
    sa.ForeignKeyConstraint(['matched_transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhooks_event_reference', 'webhooks_received', ['gateway_id', 'event_reference'], unique=False)
    op.create_index('ix_webhooks_gateway_received', 'webhooks_received', ['gateway_id', 'received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhooks_gateway_received', table_name='webhooks_received')
    op.drop_index('ix_webhooks_event_reference', table_name='webhooks_received')
    op.drop_table('webhooks_received')
    op.drop_table('tokens')
    op.drop_index('ix_api_call_logs_transaction', table_name='api_call_logs')
    op.drop_index('ix_api_call_logs_gateway_started', table_name='api_call_logs')
    op.drop_table('api_call_logs')
    op.drop_index('ix_transactions_status', table_name='transactions')
    op.drop_index('ix_transactions_merchant_reference', table_name='transactions')
    op.drop_index('ix_transactions_gateway_order_id', table_name='transactions')
    op.drop_index('ix_transactions_gateway_created', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('gateway_credentials')
    op.drop_index('ix_benchmark_runs_gateway_started', table_name='benchmark_runs')
    op.drop_table('benchmark_runs')
    op.drop_table('users')
    op.drop_table('integration_types')
    op.drop_table('gateways')
    # ### end Alembic commands ###
