"""Initial BuraPay schema.

Every table from specification section 19 plus users, app_settings, webhook_events
and gateway_health_checks. Written by Alembic autogenerate from the SQLAlchemy
models; the naming convention in app/db/base.py is what keeps constraint names
stable across environments.

Revision ID: ab4d07a46a2e
Revises: 
Create Date: 2026-08-19 22:15:55.269124
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ab4d07a46a2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings'))
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_settings_key'), ['key'], unique=True)

    op.create_table('comparison_tests',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('integration_type', sa.String(length=20), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transactions_per_gateway', sa.Integer(), nullable=False),
    sa.Column('gateway_codes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('run_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comparison_tests'))
    )
    op.create_table('gateway_health_checks',
    sa.Column('gateway_code', sa.String(length=50), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gateway_health_checks'))
    )
    with op.batch_alter_table('gateway_health_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gateway_health_checks_checked_at'), ['checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gateway_health_checks_gateway_code'), ['gateway_code'], unique=False)

    op.create_table('gateways',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('supports_hpp', sa.Boolean(), nullable=False),
    sa.Column('supports_direct', sa.Boolean(), nullable=False),
    sa.Column('supported_currencies', sa.JSON(), nullable=False),
    sa.Column('logo_slug', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('docs_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gateways'))
    )
    with op.batch_alter_table('gateways', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gateways_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('benchmark_runs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gateway_id', sa.String(length=32), nullable=True),
    sa.Column('comparison_test_id', sa.String(length=32), nullable=True),
    sa.Column('integration_type', sa.String(length=20), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('interval_seconds', sa.Float(), nullable=False),
    sa.Column('methodology', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('run_metadata', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comparison_test_id'], ['comparison_tests.id'], name=op.f('fk_benchmark_runs_comparison_test_id_comparison_tests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateways.id'], name=op.f('fk_benchmark_runs_gateway_id_gateways'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_runs'))
    )
    with op.batch_alter_table('benchmark_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benchmark_runs_comparison_test_id'), ['comparison_test_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_benchmark_runs_gateway_id'), ['gateway_id'], unique=False)

    op.create_table('gateway_credentials',
    sa.Column('gateway_id', sa.String(length=32), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=False),
    sa.Column('field_names', sa.JSON(), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateways.id'], name=op.f('fk_gateway_credentials_gateway_id_gateways'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gateway_credentials')),
    sa.UniqueConstraint('gateway_id', 'environment', name='uq_gateway_credentials_gateway_id')
    )
    with op.batch_alter_table('gateway_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gateway_credentials_gateway_id'), ['gateway_id'], unique=False)

    op.create_table('transactions',
    sa.Column('benchmark_run_id', sa.String(length=32), nullable=True),
    sa.Column('gateway_id', sa.String(length=32), nullable=False),
    sa.Column('gateway_code', sa.String(length=50), nullable=False),
    sa.Column('gateway_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('merchant_reference', sa.String(length=255), nullable=False),
    sa.Column('integration_type', sa.String(length=20), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_duration_ms', sa.Float(), nullable=True),
    sa.Column('gateway_api_time_ms', sa.Float(), nullable=True),
    sa.Column('three_ds_time_ms', sa.Float(), nullable=True),
    sa.Column('customer_interaction_time_ms', sa.Float(), nullable=True),
    sa.Column('redirect_time_ms', sa.Float(), nullable=True),
    sa.Column('page_load_time_ms', sa.Float(), nullable=True),
    sa.Column('webhook_latency_ms', sa.Float(), nullable=True),
    sa.Column('app_overhead_ms', sa.Float(), nullable=True),
    sa.Column('api_call_count', sa.Integer(), nullable=False),
    sa.Column('error_category', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('gateway_response_code', sa.String(length=50), nullable=True),
    sa.Column('gateway_response_message', sa.Text(), nullable=True),
    sa.Column('methodology', sa.String(length=20), nullable=False),
    sa.Column('webhook_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_run_id'], ['benchmark_runs.id'], name=op.f('fk_transactions_benchmark_run_id_benchmark_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateways.id'], name=op.f('fk_transactions_gateway_id_gateways'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_benchmark_run_id'), ['benchmark_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_error_category'), ['error_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_gateway_code'), ['gateway_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_gateway_id'), ['gateway_id'], unique=False)
        batch_op.create_index('ix_transactions_gateway_integration', ['gateway_id', 'integration_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_gateway_transaction_id'), ['gateway_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_merchant_reference'), ['merchant_reference'], unique=False)
        batch_op.create_index('ix_transactions_started_at', ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)

    op.create_table('api_measurements',
    sa.Column('transaction_id', sa.String(length=32), nullable=False),
    sa.Column('gateway_id', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('operation_name', sa.String(length=120), nullable=False),
    sa.Column('normalized_operation', sa.String(length=40), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('http_method', sa.String(length=10), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('gateway_response_code', sa.String(length=50), nullable=True),
    sa.Column('gateway_response_message', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_category', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timed_out', sa.Boolean(), nullable=False),
    sa.Column('is_setup_call', sa.Boolean(), nullable=False),
    sa.Column('request_size_bytes', sa.Integer(), nullable=True),
    sa.Column('response_size_bytes', sa.Integer(), nullable=True),
    sa.Column('response_snippet', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateways.id'], name=op.f('fk_api_measurements_gateway_id_gateways'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_api_measurements_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_measurements'))
    )
    with op.batch_alter_table('api_measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_measurements_gateway_id'), ['gateway_id'], unique=False)
        batch_op.create_index('ix_api_measurements_gw_op', ['gateway_id', 'normalized_operation'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_measurements_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('browser_measurements',
    sa.Column('transaction_id', sa.String(length=32), nullable=False),
    sa.Column('metric_name', sa.String(length=80), nullable=False),
    sa.Column('value_ms', sa.Float(), nullable=False),
    sa.Column('origin_scope', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_browser_measurements_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_browser_measurements'))
    )
    with op.batch_alter_table('browser_measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_browser_measurements_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('transaction_events',
    sa.Column('transaction_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('offset_ms', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_transaction_events_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_events'))
    )
    with op.batch_alter_table('transaction_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_events_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('webhook_events',
    sa.Column('gateway_code', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.String(length=32), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=True),
    sa.Column('signature_verified', sa.Boolean(), nullable=True),
    sa.Column('merchant_reference', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_webhook_events_transaction_id_transactions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events'))
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_events_gateway_code'), ['gateway_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_merchant_reference'), ['merchant_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_merchant_reference'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_gateway_code'))

    op.drop_table('webhook_events')
    with op.batch_alter_table('transaction_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_events_transaction_id'))

    op.drop_table('transaction_events')
    with op.batch_alter_table('browser_measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_browser_measurements_transaction_id'))

    op.drop_table('browser_measurements')
    with op.batch_alter_table('api_measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_measurements_transaction_id'))
        batch_op.drop_index('ix_api_measurements_gw_op')
        batch_op.drop_index(batch_op.f('ix_api_measurements_gateway_id'))

    op.drop_table('api_measurements')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index('ix_transactions_started_at')
        batch_op.drop_index(batch_op.f('ix_transactions_merchant_reference'))
        batch_op.drop_index(batch_op.f('ix_transactions_gateway_transaction_id'))
        batch_op.drop_index('ix_transactions_gateway_integration')
        batch_op.drop_index(batch_op.f('ix_transactions_gateway_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_gateway_code'))
        batch_op.drop_index(batch_op.f('ix_transactions_error_category'))
        batch_op.drop_index(batch_op.f('ix_transactions_benchmark_run_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('gateway_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gateway_credentials_gateway_id'))

    op.drop_table('gateway_credentials')
    with op.batch_alter_table('benchmark_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benchmark_runs_gateway_id'))
        batch_op.drop_index(batch_op.f('ix_benchmark_runs_comparison_test_id'))

    op.drop_table('benchmark_runs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('gateways', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gateways_code'))

    op.drop_table('gateways')
    with op.batch_alter_table('gateway_health_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gateway_health_checks_gateway_code'))
        batch_op.drop_index(batch_op.f('ix_gateway_health_checks_checked_at'))

    op.drop_table('gateway_health_checks')
    op.drop_table('comparison_tests')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_key'))

    op.drop_table('app_settings')
    # ### end Alembic commands ###
